# Site settings
title: Sasha Vladimirskiy
email: sasha@butchershop.co
description: > # this means to ignore newlines until "baseurl:"
    I'm a web developer and artist living in San Francisco, CA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shurik.github.io" # the base hostname & protocol for your site
twitter_username: sasha
github_username:  shurik

# Build settings
markdown: kramdown
